apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator-prod
          image: curlimages/curl:latest
          command: [sh, -xec]
          args:
            - |
              while true; do
                  status_code=$(curl -s -o /dev/null -w "%{http_code}" http://blue-green-prod.default.svc.cluster.local)

                  if [[ $status_code -eq 200 ]]; then
                      echo -e "\033[32m$status_code\033[0m"
                  else
                      echo -e "\033[31m$status_code\033[0m"
                  fi

                  sleep 2
              done
      restartPolicy: Always
# wrk -t5 -c10 -d2h http://blue-green-prod.default.svc.cluster.local
