apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator-prod
          image: ellerbrock/alpine-bash-curl-ssl
          command:
            [
              "sh",
              "-c",
              "while true; do curl -s -o /dev/null -w '%{http_code}' http://blue-green.default.svc.cluster.local && echo -e '\033[0;32mSuccess\033[0m' || echo -e '\033[0;31mFailure\033[0m'; sleep 5; done",
            ]
        - name: endpoint-checker-preview
          image: ellerbrock/alpine-bash-curl-ssl
          command:
            [
              "sh",
              "-c",
              "while true; do curl -s -o /dev/null -w '%{http_code}' http://blue-green-preview.default.svc.cluster.local || echo -e '\033[0;31mFailure\033[0m'; echo -e '\033[0;32mSuccess\033[0m'; sleep 5; done",
            ]
