apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator-prod
          image: argoproj/load-tester:latest
          command: [sh, -xec]
          args:
            - |
              wrk -t5 -c10 -d2h http://blue-green-prod.default.svc.cluster.local
      restartPolicy: Always
