apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traffic-generator
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/traffic
    repoURL: http://gitea-http.default.svc.cluster.local:3000/ray/progressive
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
