# This example demonstrates a Rollout using the blue-green update strategy, which contains a manual
# gate before promoting the new stack.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green
  labels:
    app: blue-green-app
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: blue-green-app
  template:
    metadata:
      labels:
        app: blue-green-app
    spec:
      containers:
        - name: blue-green
          image: app:v2
          imagePullPolicy: Never
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
          ports:
            - containerPort: 3000
  strategy:
    blueGreen:
      activeService: blue-green-prod

      previewService: blue-green-preview

      autoPromotionEnabled: true

      previewReplicaCount: 2

      scaleDownDelaySeconds: 30

      # prePromotionAnalysis:
      #   templates:
      #     - templateName: smoke-test-success
      #     - templateName: performance
      #   args:
      #     - name: service-name
      #       value: blue-green-preview.default.svc.cluster.local
      #     - name: version
      #       value: v2

      postPromotionAnalysis:
        templates:
          - templateName: smoke-test-success
