# This example demonstrates a Rollout using the blue-green update strategy, which contains a manual
# gate before promoting the new stack.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green
  labels:
    app: blue-green-app
spec:
  replicas: 5
  
  # The number of old ReplicaSets to retain.
  # Defaults to 10
  revisionHistoryLimit: 2

  # The rollback window provides a way to fast track deployments to
  rollbackWindow:
    revisions: 1

  # Pause allows a user to manually pause a rollout at any time.
  paused: true

  selector:
    matchLabels:
      app: blue-green-app
  template:
    metadata:
      labels:
        app: blue-green-app
    spec:
      containers:
        - name: blue-green
          image: app:v1
          imagePullPolicy: Never
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
          ports:
            - containerPort: 3000
  
  
  # The maximum time in seconds in which a rollout must make progress during
  # an update, before it is considered to be failed
  progressDeadlineSeconds: 180

  # Whether to abort the update when ProgressDeadlineSeconds is exceeded.
  # Optional and default is false.
  progressDeadlineAbort: true
  
  strategy:
    blueGreen:
      activeService: blue-green-prod

      previewService: blue-green-preview

      # Indicates if the rollout should automatically promote the new ReplicaSet
      # to the active service or enter a paused state.
      autoPromotionEnabled: false

      # The number of replicas to run under the preview service before the switchover.
      previewReplicaCount: 1

      # Adds a delay before scaling down the previous ReplicaSet.
      scaleDownDelaySeconds: 30

      # Limits the number of old RS that can run at once before getting scaled
      # down. Defaults to nil
      scaleDownDelayRevisionLimit: 1

      # prePromotionAnalysis:
      #   templates:
      #     - templateName: smoke-test
      #     - templateName: always-pass
      #   args:
      #     - name: service-name
      #       value: blue-green-preview.default.svc
      #     - name: version
      #       value: v2

      # postPromotionAnalysis:
      #   templates:
      #     - templateName: always-pass
      #     - templateName: success-rate
      #     - templateName: performance
      #     - templateName: payload
      #   args:
      #     - name: version
      #       value: v2
