apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: canary-app
  workloadRef: # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: canary-app
  revisionHistoryLimit: 0
  strategy:
    canary:
      abortScaleDownDelaySeconds: 5
      dynamicStableScale: true
      canaryService: canary-preview
      stableService: canary-prod
      trafficRouting:
        nginx:
          stableIngress: canary-prod
          additionalIngressAnnotations: # optional
            canary-by-header: X-Canary
            canary-by-header-value: commit-hash
      stableMetadata:
        labels:
          role: prod
      canaryMetadata:
        labels:
          role: preview

      steps:
        # 1 Pod Zero traffic
        - setWeight: 60

        # Run analysis that will always fail
        - analysis:
            templates:
              - templateName: always-pass

        # Pause Indefinitely
        - pause: {}

        # Run analysis that will always fail
        - analysis:
            templates:
              - templateName: always-pass
              - templateName: always-fail

        # Full release
        - setWeight: 100
