# This example demonstrates a Rollout using the canary update strategy, which contains a manual
# gate before promoting the new stack.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary
  labels:
    app: canary-app
    version: v1
spec:
  replicas: 10
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
    spec:
      containers:
        - name: canary
          image: app:v1
          imagePullPolicy: Never
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
          ports:
            - containerPort: 3000
  strategy:
    canary:
      stableMetadata:
        labels:
          role: prod
      canaryMetadata:
        labels:
          role: preview
      # analysis:
      #   templates:
      #     - templateName: performance
      dynamicStableScale: true
      # scaleDownDelaySeconds: 300
      # abortScaleDownDelaySeconds: 600
      # maxUnavailable: 2
      scaleDownDelayRevisionLimit: 2
      maxSurge: 10%
      # trafficRouting
      canaryService: canary-preview
      stableService: canary-prod

      # Keep running performance test in the background
      analysis:
        templates:
          - templateName: performance
        args:
          - name: version
            value: metadata.labels['version']

      trafficRouting:
        nginx:
          stableIngress: canary-prod

      # Release steps
      steps:
        # Scale initial production traffic to 0
        - setWeight: 0
        # Smoke Test it
        - analysis:
            templates:
              - templateName: success-rate
            args:
              - name: version
                value: metadata.labels['version']
        # Scale  production traffic to 20
        - setWeight: 20
        # Pause for manual approval
        # - pause: {}

        # Pause for a set time
        - pause:
            duration: 10m
