apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: payload
spec:
  args:
    - name: version
  metrics:
    - name: measure
      interval: 1m
      failureCondition: result > 0.1
      successCondition: isNaN(result) || result < 0.1
      failureLimit: 3
      count: 5
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            (histogram_quantile(0.95, sum(rate(http_response_length_bytes_bucket{version="{args.version}"}[5m])) by (le)) /
            histogram_quantile(0.95, sum(rate(http_response_length_bytes_bucket{version!="{args.version}"}[5m]))) > 0.1 
