apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: payload
spec:
  args:
    - name: version
  metrics:
    - name: payload-measurement
      interval: 1m
      initialDelay: 1m
      failureCondition: len(result) > 0 && result[0] > 0.1
      successCondition: (len(result) > 0 &&  isNaN(result[0])) || result[0] < 0.1
      failureLimit: 3
      count: 5
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
               (histogram_quantile(0.95, sum(rate(http_response_length_bytes_bucket{version="{{args.version}}"}[20m])) by (le))) / 
               (histogram_quantile(0.95, sum(rate(http_response_length_bytes_bucket{version!="{{args.version}}"}[20m])) by (le)))
