apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: performance
spec:
  args:
    - name: version
  metrics:
    - name: requests_served_in_seconds
      interval: 1m
      # 95% of requests are served within seconds
      successCondition: result[0] >= 0.095
      failureLimit: 3
      count: 5
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{version="{{args.version}}"}[5m])) by (le))
