apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: performance
spec:
  args:
    - name: version
    - name: service-name
  metrics:
    - name: traffic
      failureLimit: 1
      provider:
        job:
          spec:
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: load-tester
                    image: argoproj/load-tester:latest
                    command: [sh, -c, -x, -e]
                    args:
                      - |
                        wrk -t5 -c10 -d2m http://{{ args.service-name }}

    - name: measure
      interval: 1m
      # NOTE: prometheus queries return results in the form of a vector.
      # So it is common to access the index 0 of the returned array to obtain the value
      successCondition: result[0] >= 0.07
      failureLimit: 3
      count: 5
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            (sum(rate(
              http_requests_duration_seconds_sum{version="{{args.version}}"}[2m]
            )) /
            sum(rate(
              http_requests_duration_seconds_count{version="{{args.version}}"}[2m]
            ))) * 1000
