kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: smoke-test
spec:
  args:
    - name: url
  metrics:
    - name: smoke
      interval: 30s
      count: 5
      failureLimit: 3
      successCondition: "result != 'error'"
      provider:
        web:
          method: GET
          timeoutSeconds: 20
          url: "http://{{ args.url }}"
          headers:
            - key: Content-Type
              value: "application/json"
          jsonPath: "{$.version}"
