kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: smoke-test-success
spec:
  args:
    - name: service-name
  metrics:
    - name: smoke
      successCondition: "result != 'error'"
      provider:
        web:
          method: GET
          timeoutSeconds: 20
          # This can be a variable passed into
          url: "http://{{ args.service-name }}"
          headers:
            - key: Content-Type
              value: "application/json"
          jsonPath: "{$.version}"

---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: smoke-test-fail
spec:
  args:
    - name: service-name
  metrics:
    - name: smoke
      initialDelay: 1m
      successCondition: "version == 'some-strange-value'"
      provider:
        web:
          method: GET
          timeoutSeconds: 20
          # This can be a variable passed into
          url: "http://{{ args.service-name }}"
          headers:
            - key: Content-Type
              value: "application/json"
          jsonPath: "{$.version}"
