apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: version
  metrics:
    - name: measure-success
      interval: 1m
      successCondition: len(result) > 0 && result[0] > 0.95
      failureLimit: 3
      count: 5
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            sum(rate(http_requests_total{version="{{args.version}}", status="2XX"}[20m]))/
            sum(rate(http_requests_total{version="{{args.version}}"}[20m]))
