apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: version
  metrics:
    - name: measure
      interval: 1m
      successCondition: result[0] > 0.95
      failureLimit: 3
      count: 5
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local
          query: |
            sum(rate(http_requests_total{version="{{version}}", status="2XX"}[2m])) /
            sum(rate(http_requests_total{version="{{version}}"}[2m]))
